// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAauN0E6p46guY7cLPp1MswiyxapiCl0V0',
    appId: '1:476426267672:web:280414d7c549f0192ce76d',
    messagingSenderId: '476426267672',
    projectId: 'flutter-7bb55',
    authDomain: 'flutter-7bb55.firebaseapp.com',
    storageBucket: 'flutter-7bb55.firebasestorage.app',
    measurementId: 'G-KDGP9STQ1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQHTNacMupoaGWd1XMCRrpL153aEiwCXo',
    appId: '1:476426267672:android:06f79608b85b6df82ce76d',
    messagingSenderId: '476426267672',
    projectId: 'flutter-7bb55',
    storageBucket: 'flutter-7bb55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNrmn5LU2qnih4eWH7NqbH2uQTgXGU5qM',
    appId: '1:476426267672:ios:78eb380842c210e42ce76d',
    messagingSenderId: '476426267672',
    projectId: 'flutter-7bb55',
    storageBucket: 'flutter-7bb55.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNrmn5LU2qnih4eWH7NqbH2uQTgXGU5qM',
    appId: '1:476426267672:ios:78eb380842c210e42ce76d',
    messagingSenderId: '476426267672',
    projectId: 'flutter-7bb55',
    storageBucket: 'flutter-7bb55.firebasestorage.app',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAauN0E6p46guY7cLPp1MswiyxapiCl0V0',
    appId: '1:476426267672:web:b369d5b90cda955b2ce76d',
    messagingSenderId: '476426267672',
    projectId: 'flutter-7bb55',
    authDomain: 'flutter-7bb55.firebaseapp.com',
    storageBucket: 'flutter-7bb55.firebasestorage.app',
    measurementId: 'G-K7HE9DEFX1',
  );
}
