// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA19v--TsGOAsIktLHdITqXcQzQmNWL3Wk',
    appId: '1:594324674348:web:9b42a9be818f32801dbe89',
    messagingSenderId: '594324674348',
    projectId: 'yuui-b20c6',
    authDomain: 'yuui-b20c6.firebaseapp.com',
    storageBucket: 'yuui-b20c6.firebasestorage.app',
    measurementId: 'G-565FF57SQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH8uYpiRxBqGgOZ2HtL65XQ-aMTQd9uzo',
    appId: '1:594324674348:android:41875a81b613da461dbe89',
    messagingSenderId: '594324674348',
    projectId: 'yuui-b20c6',
    storageBucket: 'yuui-b20c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDMUbL7kJG-_AABAtWM5bgdzUUenENb7g',
    appId: '1:594324674348:ios:caa447852bbf16091dbe89',
    messagingSenderId: '594324674348',
    projectId: 'yuui-b20c6',
    storageBucket: 'yuui-b20c6.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDMUbL7kJG-_AABAtWM5bgdzUUenENb7g',
    appId: '1:594324674348:ios:caa447852bbf16091dbe89',
    messagingSenderId: '594324674348',
    projectId: 'yuui-b20c6',
    storageBucket: 'yuui-b20c6.firebasestorage.app',
    iosBundleId: 'com.example.chatify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA19v--TsGOAsIktLHdITqXcQzQmNWL3Wk',
    appId: '1:594324674348:web:44d77214a25dac5c1dbe89',
    messagingSenderId: '594324674348',
    projectId: 'yuui-b20c6',
    authDomain: 'yuui-b20c6.firebaseapp.com',
    storageBucket: 'yuui-b20c6.firebasestorage.app',
    measurementId: 'G-VJTKC7M54E',
  );
}
